---
title: "R Notebook"
output: html_notebook
---
````{R carga}
DF = read.table("01A_AlzheimerDisease.txt", header = TRUE, sep = "\t", dec = ".", check.names = FALSE)

````

## Descripición y naturaleza de las variables

````{R variables}
tabla_variables = data.frame(variable = colnames(DF), tipo= c(
  rep("numerical", 14),
  "integer",
  rep("numerical", 12),
  "char",
  "numerical",
  rep("char",2)))
````

La cantidad actual de filas u observaciones de la BBDD es actualmente `r nrow(DF)`
y la cantidad actual de columnas o variables `r ncol(DF)`

````{R limpieza}
var_categoricas <- colnames(DF)[!sapply(DF, is.numeric)]
print(var_categoricas)

##EDAD SALE ALGO RARO, SALEN TODOS CON VALOR 0,98 , HAY QUE TENER CUIDADO CON ESTA VARIABLE PORQUE IGUAL SESGA LOS RESULTADOS
````
  
````{r CTES, ECHO = TRUE}
summary(DF[,tabla_variables$variable[tabla_variables$tipo == "numerical"]])

# Primero vamos a coger las columnas numéricas de nuestro dataset
numericas = DF[,tabla_variables$variable[tabla_variables$tipo == "numerical"]]
numericas
colnames(numericas)
cor(numericas)
mySD = apply(numericas, 2, sd) # así sacamos para todas las variables su desv. típica
myMean = colMeans(numericas) # así sacamos para todas las variables su media
myCV = mySD/myMean # y obtenemos el coeficiente de variación
myCV
# Vamos a tomar como criterio para eliminar variables que estas tengan un CV menor que 0.1
sort(myCV)

apply(DF[,tabla_variables$variable[tabla_variables$tipo == "binary"]], 2, table, useNA = "i")

apply(DF[,tabla_variables$variable[tabla_variables$tipo == "categorical"]], 2, table, useNA = "i")

apply(DF[,tabla_variables$variable[tabla_variables$tipo == "categorical"]], 2,
      function (x) round(100*table(x)/sum(table(x)), 2))

alzhsin = subset(DF, select = -c(age, IGF_BP_2, RANTES, tau))
````
````{R SUBSET}
DFsub2 = subset(DF, select = -c(CgA))
DF = subset(DF, select = -c(CgA))
tabla_variables = subset(tabla_variables, variable != "CgA")
````

````{r factor}
DF$gender = factor(DF$gender)
DF$diagnosis = factor(DF$diagnosis)
````

````{r anomalo, echo = TRUE}
boxplot(DFsub2[, tabla_variables$variable[tabla_variables$tipo == "numerical"]], las = 2)
````
